### PR TITLE
Use request-promise for config http requests

### PR DESCRIPTION
**Pull request by kroikie**
With `request-promise` exposing response features like errors are easier. So switching from `https` to `request-promise` for http requests in the config sample.

### CODE REVIEW

**Comment by samtstern** [comment]
This is a funny follow up to #32

**Comment by samtstern** [comment]
LGTM.  Would love an opinion from @davideast or @nicolasgarnier or @abehaskins on what is most popular to use though.

I have used:
  * [`request-promise-native`](https://www.npmjs.com/package/request-promise-native)
  * [`axios`](https://www.npmjs.com/package/axios)
  * [`node-fetch`](https://www.npmjs.com/package/node-fetch)

**Comment by clp93** [comment]
LGTM. Thanks Arthur!

**Comment by samtstern** [comment]
@kroikie bump, want to merge this?

**Pull request merged**
