### PR TITLE
Update index.js  (fixed export)

### PR DESCRIPTION
**Pull request by nitinsurana**

### CODE REVIEW

**Comment by nitinsurana** [comment]
@googlebot I signed it!

**Comment by samtstern** [comment]
The googleapis package uses the `{ google }` import style:
https://www.npmjs.com/package/googleapis#first-example

Can you explain why you made this change?

**Comment by nitinsurana** [comment]
Cloned the repo and tried running it, didn't work. Couldn't find "google"
to export, it was null.

Looked at the source code and "google" isn't exported.
Updated it as per the PR and the repo works fine now.

**Comment by samtstern** [comment]
@nitinsurana good catch!  Looks like we have a very old version of `googleapis`.  I will merge your PR and then send a new one to update the version.

**Pull request merged**
