### PR TITLE
Update index.js

### LINKED ISSUE #10: Firebase 3.0
Allo! Could you please update this to firebase 3? I mean use firebase-admin instead of firebase:
var firebase = require('firebase-admin');
firebase.initializeApp({
  credential: firebase.credential.cert(serviceAccount),
  databaseURL:"https://URL.firebaseio.com"
})

In firebase official page the update is already did :)
Thanks,
Laura

### PR DESCRIPTION
**Pull request by dwberry**
Updated to Credential and firebase-admin to match documentation at  https://firebase.google.com/docs/admin/setup.

fixes #10

### CODE REVIEW

**Comment by dwberry** [comment]
I signed the CLA.

**Comment by nicolasgarnier** [comment]
Thanks @dwberry! Could you also update the **package.json** file so that it imports the `firebase-admin` package instead of `firebase` ?

Thanks!

**Comment by dwberry** [comment]
OK
Try that.

I debated on updating the `firebase` var to "admin" to be more consistent with the docs, but I can to the conclusion if you are just starting as this repo intends then is isn't needed.

**Comment by nicolasgarnier** [comment]
Looks good! Thanks so much @dwberry

**Pull request merged**
