### PR TITLE
remote-config- added support for 'validate_only'

### PR DESCRIPTION
**Pull request by inteist**
to be able to validate the new config before publishing it

visual studio code screwed up formatting, not sure if that's important or not.

### CODE REVIEW

**Comment by nicolasgarnier** [comment]
Thanks for this @inteist however we'll need to keep the original code formatting :)

Could you update your PR with only the minimal code change? :)

Assigning to @kroikie for review

**Comment by inteist** [comment]
@nicolasgarnier, sorry I do not have the time. I wasn't implying that you keep that formatting, I pointed that out to make sure the sheer volume of changes doesn't seem overwhelming since most of it is formatting. 

and I wan't going to spend on this more time fighting the tools (the editor) more than I needed. 

The changes can be extracted and applied by the reviewer. There is not so many material changes.

*** As a sidenote  isn't clear from documentation but the smarter/better thing to do would be to run validation before any publish action and if validation fails. -return an error on publish attempt with descriptive error message. Doing this however will simply render the parameter and need to run validation beforehand non relevant. 

To be honest this project felt very rough to me - e.g. errors logged not even being defined/present in the response.

**Comment by inteist** [comment]
signed

**Comment by kroikie** [comment]
@inteist thanks for the PR, I'll apply it in a follow up PR if you are not able to complete this one.

**Comment by kroikie** [comment]
@inteist I'll close this PR since it is in conflict with master. Feel free to rebase and submit a subsequent PR.

**Pull request closed without merging**
