### PR TITLE
Update firebase packages

### PR DESCRIPTION
**Pull request by yashmurty**
### Changes:
- Update `firebase-admin` package.
- Update `firebase-functions` package.

The `firebase emulator` throws errors with the current version values.
```
The Cloud Functions emulator requires the module "firebase-functions" to be version >3.3.0 so your version is too old.
```

### CODE REVIEW

**Comment by samtstern** [comment]
cc @markarndt

**Comment by samtstern** [comment]
@yashmurty thank you!

**Comment by markarndt** [comment]
Yes many thanks.

@samtstern, this is a fork of emulators-codelab needed by Learn Assistant. Uf you have any warnings about how *not* to PR these files over into emulators-codelab:master and how they should live alongside the Codelab versions there, please let me know.

**Comment by samtstern** [comment]
@markarndt maybe we should just make `cs-walkthrough` a permanent folder on `master` rather than relying on a long-lived branch?

**Comment by markarndt** [comment]
@samtstern  Just to make sure .... you're ok having a `cs-walkthrough` folder alongside `codelab-initial-state` and `codelab-final-state` in emulators-codelab? If so, I'll do PRs to remove here and create over there.

**Comment by samtstern** [comment]
Yeah that’s cool with me!

**Pull request merged**
